name: Publish

on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
    tags:
      - v*.*.*

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - name: Install Yarn
        run: corepack install --global yarn@3.8.5
      - name: Cache Yarn Releases
        uses: actions/cache@v2
        with:
          path: .yarn/releases
          key: yarn-${{ hashFiles('.yarnrc.yml') }}
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install --immutable
      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Publish web package
        run: npx nx run web:nx-release-publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      - name: Publish mobile package
        run: npx nx run mobile:nx-release-publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
